version: '3.8'

services:
  app:
    build: ./  
    command: streamlit run /app/app.py  
    volumes:
      - ./app:/app 
      - ./yolo_results:/yolo_results  
      - ./feedback_frames:/feedback_frames  
      - ./models:/models  
    ports:
      - "8501:8501"  
    environment:
      - PYTHONUNBUFFERED=1 
    networks:
      - dispatch-network  

networks:
  dispatch-network:
    driver: bridge
